# action.yml
name: 'Crawler action'
description: 'Crawls website using wget and gets all links'
inputs:
  start-url:  # id of input
    description: 'Url to crawl for links'
    required: true
    default: 'https://open-horizon.github.io/'
outputs:
  crawled-urls: # id of output
    description: 'Urls received after crawling'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.start-url }}
