on: [push]

jobs:
  crawler_job:
    runs-on: ubuntu-latest
    name: A job to crawl website for links
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Crawler action step
        uses: ./ # Uses an action in the root directory
        id: crawler
        with:
          start-url: https://open-horizon.github.io/
      # Use the output from the `hello` step
      - name: Get the orphan pages
        run: echo "The time was ${{ steps.hello.outputs.orphan-pages }}"